import os
# import logging
# from scripts import ssh_tunnel
"""
Django settings for saswat_cust_info project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$5m!@8&k@4rtj3f+(sxk5xy9!6zpqf$uz)k_c=m1fi%pql-wb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'saswat_cust_app',
    'rest_framework.authtoken',
    'data_entry_app',
    'dms',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'debug_toolbar.middleware.DebugToolbarMiddleware'

]

INTERNAL_IPS = [
    '127.0.0.1',
]

"""
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
}
"""

ROOT_URLCONF = 'saswat_cust_info.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saswat_cust_info.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#anuj local

DATABASES = {
    'default':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_app_db',
            'USER': 'postgres',
            'PASSWORD': 'admin',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5433,
        },


    'sqlit': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dataentry_db',
            'USER': 'postgres',
            'PASSWORD': 'admin',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5433,
    }, 
    
    'dms':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dms_db',
            'USER': 'postgres',
            'PASSWORD': 'admin',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5433,
        }


}



#KAKA Saheb local
"""
DATABASES = {
    'default':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_app_db',
            'USER': 'postgres',
            'PASSWORD': 'Tara@123',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'sqlit':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dataentry_db',
            'USER': 'postgres',
            'PASSWORD': 'Tara@123',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'dms':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dms_db',
            'USER': 'postgres',
            'PASSWORD': 'Tara@123',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        }
    
}

"""

"""


#Shailesh local

DATABASES = {
    'default':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_app_db',
            'USER': 'postgres',
            'PASSWORD': 'postgres_pwd',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'sqlit':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dataentry_db',
            'USER': 'postgres',
            'PASSWORD': 'postgres_pwd',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'dms':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dms_db',
            'USER': 'postgres',
            'PASSWORD': 'postgres_pwd',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        }

}

"""

"""
#Harshitha local

DATABASES = {
    'default':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_app_db',
            'USER': 'postgres',
            'PASSWORD': 'Harsha',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'sqlit':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dataentry_db',
            'USER': 'postgres',
            'PASSWORD': 'Harsha',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        },

    'dms':
        {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'saswat_dms_db',
            'USER': 'postgres',
            'PASSWORD': 'Harsha',  # Tara@123
            'HOST': 'localhost',
            'PORT': 5432,
        }

}
"""


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'saswat_cust_app', 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    # 'PAGE_SIZE': 1,
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DATABASE_ROUTERS = ['routers.SaswatCustAppRouter', 'routers.DataEntryAppRouter', 'routers.DmsRouter']
# settings.py


FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB in bytes

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 5MB in bytes

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler', # Using StreamHandler to output logs to console
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }


# LOG_DIR = '/var/lib/jenkins/workspace/04_Saswat_login_CICD/logs'
LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Create the directory if it doesn't exist
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Set to INFO or higher for production
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',  # Set to INFO or higher for production
            'propagate': True,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
}

"""
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]
"""

SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'saswat_cust_app.urls.api_info',
}



# --------------- EXTERNAL APIS ----------------#


OTP_API_URL = 'http://ci1.saswatfinance.com:8084/api/otp'


INITIATE_PAYMENT_URL = 'https://98.70.77.51:8083/autopay/api/saswat/initiate-payment'
DEBIT_REQUEST_URL = 'http://98.70.76.243:8084/collect/saswat/debitRequest'
TRANSACTION_STATUS_URL = 'http://98.70.76.243:8084/collect/saswat/Transactionstatus'
CANCEL_MANDATE_URL = 'http://98.70.76.243:8084/collect/saswat/cancel-mandate'
